SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 100
PLAYER_SPEED = 100
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SLASH_COOLDOWN = 0.3
PLAYER_SLASH_SPEED = 1500

SHOT_RADIUS = 5
SLASH_RADIUS = 20

ANIMATION_TIME_SLASH = 0.2
